blueprint:
##############################################################
  name: Various Zigbee Wireless Switch
  description: >-
    ## Supported Device - (confirmed working)
    
      Tuya 
        - [TS0044](https://www.zigbee2mqtt.io/devices/TS0044.html)

      Sihas 
        - [SBM300ZC4](https://www.zigbee2mqtt.io/devices/SBM300ZC4.html#shinasystem-sbm300zc4) - Wireless 4gang
      
      Aqara
        - [WXKG04LM](https://www.zigbee2mqtt.io/devices/WXKG04LM.html#aqara-wxkg04lm) - Wireless remote switch T1 (double rocker)
        - [WXKG13LM](https://www.zigbee2mqtt.io/devices/WXKG13LM.html#aqara-wxkg13lm) - Wireless mini switch T1
      iKea
        - [E2001/E2002](https://www.zigbee2mqtt.io/devices/E2001_E2002.html) - STYRBAR remote control

    ## Prerequisites
        Ensure all wireless switches are connected to `Zigbee2MQTT`
        
    ## User Manual
      
      1. If you haven’t changed the topic in Zigbee2MQTT, you don’t need to modify the base topic.
        Leave it as the `default` value.
      
      2. Type the `FRIENDLY NAME` of the wireless switch you want to control into the device input.
        2-1. Dropdown selection is not available; manual typing is required.
        2-2. It must be the `Friendly Name`, not the Entity ID!
        2-3. It’s not certain, but it’s recommended to change the friendly name in Zigbee2MQTT and use that value. 
          If you’ve arbitrarily changed the friendly name in the Home Assistant UI, it might not work as expected

      3. Create automation actions. Done!
      

       # NOTE!
       If you’re unsure where to place the button’s action, please refer to my [GitHub README](https://github.com/kkqq9320/homeassistant/blob/main/README.md)

        - The RELEASE action of all buttons DOES NOT WORK
        
        - The actions of AQARA MINI should only be placed in 1_*_action. (* = single, double, hold)
        
        - The BOTH CLICK action of Aqara T1 should be placed in 3_*_action. (* = single, double, hold)


      ### For debugging note;
      
        * If you want to know the details about the button action states, go to "/config/blueprints/automation/kkqq9320/various_zigbee_wireless_switch.yaml"

    <!--
    # Working trigger actions payload (work as {{ action }}) + except `release` action
      # Tuya(TS0044)
      # x = 1,2,3,4
      # x_single
      # x_double
      # x_hold
      
      # Sihas 
      # x = 1,2,3,4
      # x_single
      # x_double
      # x_long
      
      # Aqara mini
      # single
      # double
      # hold
      ## release
      
      # Aqara double rocker
      # x = 1,2,3
      # button_x_single
      # button_x_double
      # button_x_hold
      ## button_x_release
    -->

  domain: automation
  input:
  
    base_topic:
      name: Base Topic
      description: >-
        The base topic configured in Zigbee2MQTT. 
        <br>If you haven't changed this, leave the default here `Zigbee2MQTT`
      default: zigbee2mqtt

    device:
      name: Device
      description: >-
        The `FRIENDLY NAME` of the Zigbee device you want to control.
        <br>(as set in `Zigbee2MQTT web UI`; `NOT` entity id`).
      selector:
        text:

    1_single_action:
      name: 1st Single
      description: Any Button, (*Mini Sholud be here)
      default: []
      selector:
        action: {}
    1_double_action:
      name: 1st Double
      description: Any Button, (*Mini Sholud be here)
      default: []
      selector:
        action: {}
    1_hold_action:
      name: 1st Hold
      description: Any Button, (*Mini Sholud be here)
      default: []
      selector:
        action: {}

    2_single_action:
      name: 2nd Single
      description: Tuya, T1, Sihas
      default: []
      selector:
        action: {}
    2_double_action:
      name: 2nd Double
      description: Tuya, T1, Sihas
      default: []
      selector:
        action: {}
    2_hold_action:
      name: 2nd Hold
      description: Tuya, T1, Sihas
      default: []
      selector:
        action: {}

    3_single_action:
      name: 3rd Single
      description: Tuya, T1, Sihas (*T1's Both action Sholud be here)
      default: []
      selector:
        action: {}
    3_double_action:
      name: 3rd Double
      description: Tuya, T1, Sihas (*T1's Both action Sholud be here)
      default: []
      selector:
        action: {}
    3_hold_action:
      name: 3rd Hold
      description: Tuya, T1, Sihas (*T1's Both action Sholud be here)
      default: []
      selector:
        action: {}

    4_single_action:
      name: 4th Single
      description: Tuya, Sihas
      default: []
      selector:
        action: {}
    4_double_action:
      name: 4th Double
      description: Tuya, Sihas
      default: []
      selector:
        action: {}
    4_hold_action:
      name: 4th Hold
      description: Tuya, Sihas
      default: []
      selector:
        action: {}

mode: parallel
max: 100
max_exceeded: silent
############################################################
trigger_variables:
  base_topic: !input base_topic
  target: !input device
############################
trigger:
  trigger: mqtt
  topic: '{{ base_topic }}/{{ target }}/action'
############################################################
action:
- variables:
    action: "{{ trigger.payload }}"
- choose:
  - conditions: "{{ action in ['on', 'single', '1_single',  'button_1_single'] }}"
    sequence: !input 1_single_action
  - conditions: "{{ action in ['double', '1_double',  'button_1_double'] }}"
    sequence: !input 1_double_action
  - conditions: "{{ action in ['brightness_move_up', 'hold', '1_hold', '1_long',  'button_1_hold'] }}"
    sequence: !input 1_hold_action

  - conditions: "{{ action in ['arrow_right_click', '2_single', 'button_2_single'] }}"
    sequence: !input 2_single_action
  - conditions: "{{ action in ['2_double', 'button_2_double'] }}"
    sequence: !input 2_double_action
  - conditions: "{{ action in ['arrow_right_hold', '2_hold', '2_long', 'button_2_hold'] }}"
    sequence: !input 2_hold_action

  - conditions: "{{ action in ['off', '3_single', 'button_3_single'] }}"
    sequence: !input 3_single_action
  - conditions: "{{ action in ['3_double', 'button_3_double'] }}"
    sequence: !input 3_double_action
  - conditions: "{{ action in ['brightness_move_down', '3_hold', '3_long', 'button_3_hold'] }}"
    sequence: !input 3_hold_action

  - conditions: "{{ action in ['arrow_left_click', '4_single', 'button_4_single'] }}"
    sequence: !input 4_single_action
  - conditions: "{{ action in ['4_double', 'button_4_double'] }}"
    sequence: !input 4_double_action
  - conditions: "{{ action in ['arrow_left_hold', '4_hold', '4_long'] }}"
    sequence: !input 4_hold_action

